---
- name: Install fish
  ansible.builtin.include_tasks: install-fish.yml

- name: Configure fish
  ansible.builtin.include_tasks: configure-fish.yml
  vars:
    fish_user: "{{ item }}"
  loop: "{{ fish_users + [ansible_user] }}"

- name: Install oh-my-fish
  ansible.builtin.include_tasks: install-omf.yml
